[project]
name = "rdfpat"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "rdflib>=7.1.1",
    "shapely>=2.0.6",
]

[dependency-groups]
dev = [
  "black",
  "pytest",
]

[tool.pytest.ini_options]
pythonpath = ["."]